id: schemas/product
kind: schema
version: 1
status: approved
title: Product Schema
tags:
    - schema
    - products
content:
    sections:
        - name: Fields
          blocks:
            - type: schema_field
              id: product_id
              name: id
              datatype: string
              required: true
              description: Unique product identifier.
              example: prod_001
            - type: schema_field
              id: name
              name: name
              datatype: string
              required: true
              description: Display name of the product.
              example: Starter Kit
            - type: schema_field
              id: price
              name: price
              datatype: decimal
              required: true
              description: Unit price in the store currency.
              example: 29.99
            - type: schema_field
              id: currency
              name: currency
              datatype: string
              required: true
              description: ISO 4217 currency code.
              example: USD
summary: |
    Product object used across catalog endpoints.
custom:
    data_classification: internal
    pii: false
reviewers:
    - name: Example Reviewer
      timestamp: 2026-02-03T21:30:00Z
      version: 1
